export default function useExamsData() {
    return [
        {
            id: 1,
            title: "Examen de Matemáticas",
            category: "Cálculo I",
            status: "pending",
            date: "2025-02-05",
            priority: "high",
            type: "exam",
            matriz: "Urgente e Importante",
        },
        {
            id: 2,
            title: "Examen de Biología",
            category: "Biología General",
            status: "completed",
            date: "2025-01-28",
            priority: "medium",
            type: "exam",
            matriz: "Importante pero No Urgente",
        },
        {
            id: 3,
            title: "Examen de Física",
            category: "Física II",
            status: "not-completed",
            date: "2025-02-12",
            priority: "low",
            type: "exam",
            matriz: "Urgente e Importante",
        },
        {
            id: 4,
            title: "Examen de Matemáticas",
            category: "Cálculo I",
            status: "pending",
            date: "2025-02-05",
            priority: "high",
            type: "exam",
            matriz: "Urgente e Importante",
        },
        {
            id: 5,
            title: "Examen de Biología",
            category: "Biología General",
            status: "completed",
            date: "2025-01-28",
            priority: "medium",
            type: "exam",
            matriz: "Importante pero No Urgente",
        },

    ];
}
